<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationIcon>icon.ico</ApplicationIcon>

        <!-- Настройки для single-file exe -->
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>false</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Npgsql" Version="10.0.1" />
        <PackageReference Include="Otp.NET" Version="1.4.0" />
        <PackageReference Include="System.Data.Odbc" Version="10.0.2" />
        <PackageReference Include="System.Management" Version="10.0.0-rc.2.25502.107" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="icon.ico">
            <LogicalName>icon.ico</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Remove="app.manifest" />
    </ItemGroup>

    <ItemGroup>
        <None Update="dashboard.html">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="releases\dashboard.html">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <Target Name="CopyToReleases" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
        <PropertyGroup>
            <ReleasesFolder>$(ProjectDir)releases\</ReleasesFolder>
        </PropertyGroup>

        <MakeDir Directories="$(ReleasesFolder)" Condition="!Exists('$(ReleasesFolder)')" />

        <Copy
                SourceFiles="$(PublishDir)$(TargetName).exe"
                DestinationFiles="$(ReleasesFolder)$(TargetName).exe"
                SkipUnchangedFiles="true" />

        <Message Text="Copied $(TargetName).exe to $(ReleasesFolder)" Importance="high" />
    </Target>

</Project>